#NoEnv
; #Warn
SendMode Input 
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

;makes sure youre not trying to type 500 books worth of text, its capped at 4kb
sizecheck(file)
{
	FileGetSize, size, %file%, K
	if (size < 4) {
	FileRead, Contents, %file%
	SendInput %Contents%
	}
return 
}

;aliases for copypastas
::navysealpasta::
file = navyseal.txt
sizecheck(file)
return

::brainpowerpasta::
file = brainpower.txt
sizecheck(file)
return

;down here are twitch emote autocorrects
::4Head::4Head
::AMPEnergy::AMPEnergy
::AMPEnergyCherry::AMPEnergyCherry
::ANELE::ANELE
::ArgieB8::ArgieB8
::ArsonNoSexy::ArsonNoSexy
::AsianGlow::AsianGlow
::AthenaPMS::AthenaPMS
::BabyRage::BabyRage
::BatChest::BatChest
::BCouch::BCouch
::BCWarrior::BCWarrior
::BibleThump::BibleThump
::BiersDerp::BiersDerp
::BigBrother::BigBrother
::BionicBunion::BionicBunion
::BlargNaut::BlargNaut
::bleedPurple::bleedPurple
::BloodTrail::BloodTrail
::BORT::BORT
::BrainSlug::BrainSlug
::BrokeBack::BrokeBack
::BudBlast::BudBlast
::BuddhaBar::BuddhaBar
::BudStar::BudStar
::ChefFrank::ChefFrank
::cmonBruh::cmonBruh
::CoolCat::CoolCat
::CorgiDerp::CorgiDerp
::CougarHunt::CougarHunt
::DAESuppy::DAESuppy
::DalLOVE::DalLOVE
::DansGame::DansGame
::DatSheffy::DatSheffy
::DBstyle::DBstyle
::deExcite::deExcite
::deIlluminati::deIlluminati
::DendiFace::DendiFace
::DogFace::DogFace
::DOOMGuy::DOOMGuy
::duDudu::duDudu
::EagleEye::EagleEye
::EleGiggle::EleGiggle
::FailFish::FailFish
::FPSMarksman::FPSMarksman
::FrankerZ::FrankerZ
::FreakinStinkin::FreakinStinkin
::FUNgineer::FUNgineer
::FunRun::FunRun
::FutureMan::FutureMan
::FuzzyOtterOO::FuzzyOtterOO
::GingerPower::GingerPower
::GrammarKing::GrammarKing
::HassaanChop::HassaanChop
::HassanChop::HassanChop
::HeyGuys::HeyGuys
::HotPokket::HotPokket
::HumbleLife::HumbleLife
::ItsBoshyTime::ItsBoshyTime
::Jebaited::Jebaited
::JKanStyle::JKanStyle
::JonCarnage::JonCarnage
::KAPOW::KAPOW
::Kappa::Kappa
::KappaClaus::KappaClaus
::KappaPride::KappaPride
::KappaRoss::KappaRoss
::KappaWealth::KappaWealth
::Keepo::Keepo
::KevinTurtle::KevinTurtle
::Kippa::Kippa
::Kreygasm::Kreygasm
::Mau5::Mau5
::mcaT::mcaT
::MikeHogu::MikeHogu
::MingLee::MingLee
::MrDestructoid::MrDestructoid
::MVGame::MVGame
::NinjaTroll::NinjaTroll
::NomNom::NomNom
::NoNoSpot::NoNoSpot
::NotATK::NotATK
::NotLikeThis::NotLikeThis
::OhMyDog::OhMyDog
::OMGScoots::OMGScoots
::OneHand::OneHand
::OpieOP::OpieOP
::OptimizePrime::OptimizePrime
::OSfrog::OSfrog
::OSkomodo::OSkomodo
::OSsloth::OSsloth
::panicBasket::panicBasket
::PanicVis::PanicVis
::PartyTime::PartyTime
::PazPazowitz::PazPazowitz
::PeoplesChamp::PeoplesChamp
::PermaSmug::PermaSmug
::PeteZaroll::PeteZaroll
::PeteZarollTie::PeteZarollTie
::PicoMause::PicoMause
::PipeHype::PipeHype
::PJSalt::PJSalt
::PMSTwin::PMSTwin
::PogChamp::PogChamp
::Poooound::Poooound
::PraiseIt::PraiseIt
::PRChase::PRChase
::PunchTrees::PunchTrees
::PuppeyFace::PuppeyFace
::RaccAttack::RaccAttack
::RalpherZ::RalpherZ
::RedCoat::RedCoat
::ResidentSleeper::ResidentSleeper
::riPepperonis::riPepperonis
::RitzMitz::RitzMitz
::RuleFive::RuleFive
::SeemsGood::SeemsGood
::ShadyLulu::ShadyLulu
::ShazBotstix::ShazBotstix
::ShibeZ::ShibeZ
::SmoocherZ::SmoocherZ
::SMOrc::SMOrc
::SMSkull::SMSkull
::SoBayed::SoBayed
::SoonerLater::SoonerLater
::SriHead::SriHead
::SSSsss::SSSsss
::StinkyCheese::StinkyCheese
::StoneLightning::StoneLightning
::StrawBeary::StrawBeary
::SuperVinlin::SuperVinlin
::SwiftRage::SwiftRage
::TBCheesePull::TBCheesePull
::TBTacoLeft::TBTacoLeft
::TBTacoRight::TBTacoRight
::TF2John::TF2John
::TheRinger::TheRinger
::TheTarFu::TheTarFu
::TheThing::TheThing
::ThunBeast::ThunBeast
::TinyFace::TinyFace
::TooSpicy::TooSpicy
::TriHard::TriHard
::TTours::TTours
::twitchRaid::twitchRaid
::UleetBackup::UleetBackup
::UncleNox::UncleNox
::UnSane::UnSane
::VaultBoy::VaultBoy
::VoHiYo::VoHiYo
::Volcania::Volcania
::WholeWheat::WholeWheat
::WinWaker::WinWaker
::WTRuck::WTRuck
::WutFace::WutFace
::YouWHY::4Head::YouWHY::4Head
::AMPEnergy::AMPEnergy
::AMPEnergyCherry::AMPEnergyCherry
::ANELE::ANELE
::ArgieB8::ArgieB8
::ArsonNoSexy::ArsonNoSexy
::AsianGlow::AsianGlow
::AthenaPMS::AthenaPMS
::BabyRage::BabyRage
::BatChest::BatChest
::BCouch::BCouch
::BCWarrior::BCWarrior
::BibleThump::BibleThump
::BiersDerp::BiersDerp
::BigBrother::BigBrother
::BionicBunion::BionicBunion
::BlargNaut::BlargNaut
::bleedPurple::bleedPurple
::BloodTrail::BloodTrail
::BORT::BORT
::BrainSlug::BrainSlug
::BrokeBack::BrokeBack
::BudBlast::BudBlast
::BuddhaBar::BuddhaBar
::BudStar::BudStar
::ChefFrank::ChefFrank
::cmonBruh::cmonBruh
::CoolCat::CoolCat
::CorgiDerp::CorgiDerp
::CougarHunt::CougarHunt
::DAESuppy::DAESuppy
::DalLOVE::DalLOVE
::DansGame::DansGame
::DatSheffy::DatSheffy
::DBstyle::DBstyle
::deExcite::deExcite
::deIlluminati::deIlluminati
::DendiFace::DendiFace
::DogFace::DogFace
::DOOMGuy::DOOMGuy
::duDudu::duDudu
::EagleEye::EagleEye
::EleGiggle::EleGiggle
::FailFish::FailFish
::FPSMarksman::FPSMarksman
::FrankerZ::FrankerZ
::FreakinStinkin::FreakinStinkin
::FUNgineer::FUNgineer
::FunRun::FunRun
::FutureMan::FutureMan
::FuzzyOtterOO::FuzzyOtterOO
::GingerPower::GingerPower
::GrammarKing::GrammarKing
::HassaanChop::HassaanChop
::HassanChop::HassanChop
::HeyGuys::HeyGuys
::HotPokket::HotPokket
::HumbleLife::HumbleLife
::ItsBoshyTime::ItsBoshyTime
::Jebaited::Jebaited
::JKanStyle::JKanStyle
::JonCarnage::JonCarnage
::KAPOW::KAPOW
::Kappa::Kappa
::KappaClaus::KappaClaus
::KappaPride::KappaPride
::KappaRoss::KappaRoss
::KappaWealth::KappaWealth
::Keepo::Keepo
::KevinTurtle::KevinTurtle
::Kippa::Kippa
::Kreygasm::Kreygasm
::Mau5::Mau5
::mcaT::mcaT
::MikeHogu::MikeHogu
::MingLee::MingLee
::MrDestructoid::MrDestructoid
::MVGame::MVGame
::NinjaTroll::NinjaTroll
::NomNom::NomNom
::NoNoSpot::NoNoSpot
::NotATK::NotATK
::NotLikeThis::NotLikeThis
::OhMyDog::OhMyDog
::OMGScoots::OMGScoots
::OneHand::OneHand
::OpieOP::OpieOP
::OptimizePrime::OptimizePrime
::OSfrog::OSfrog
::OSkomodo::OSkomodo
::OSsloth::OSsloth
::panicBasket::panicBasket
::PanicVis::PanicVis
::PartyTime::PartyTime
::PazPazowitz::PazPazowitz
::PeoplesChamp::PeoplesChamp
::PermaSmug::PermaSmug
::PeteZaroll::PeteZaroll
::PeteZarollTie::PeteZarollTie
::PicoMause::PicoMause
::PipeHype::PipeHype
::PJSalt::PJSalt
::PMSTwin::PMSTwin
::PogChamp::PogChamp
::Poooound::Poooound
::PraiseIt::PraiseIt
::PRChase::PRChase
::PunchTrees::PunchTrees
::PuppeyFace::PuppeyFace
::RaccAttack::RaccAttack
::RalpherZ::RalpherZ
::RedCoat::RedCoat
::ResidentSleeper::ResidentSleeper
::riPepperonis::riPepperonis
::RitzMitz::RitzMitz
::RuleFive::RuleFive
::SeemsGood::SeemsGood
::ShadyLulu::ShadyLulu
::ShazBotstix::ShazBotstix
::ShibeZ::ShibeZ
::SmoocherZ::SmoocherZ
::SMOrc::SMOrc
::SMSkull::SMSkull
::SoBayed::SoBayed
::SoonerLater::SoonerLater
::SriHead::SriHead
::SSSsss::SSSsss
::StinkyCheese::StinkyCheese
::StoneLightning::StoneLightning
::StrawBeary::StrawBeary
::SuperVinlin::SuperVinlin
::SwiftRage::SwiftRage
::TBCheesePull::TBCheesePull
::TBTacoLeft::TBTacoLeft
::TBTacoRight::TBTacoRight
::TF2John::TF2John
::TheRinger::TheRinger
::TheTarFu::TheTarFu
::TheThing::TheThing
::ThunBeast::ThunBeast
::TinyFace::TinyFace
::TooSpicy::TooSpicy
::TriHard::TriHard
::TTours::TTours
::twitchRaid::twitchRaid
::UleetBackup::UleetBackup
::UncleNox::UncleNox
::UnSane::UnSane
::VaultBoy::VaultBoy
::VoHiYo::VoHiYo
::Volcania::Volcania
::WholeWheat::WholeWheat
::WinWaker::WinWaker
::WTRuck::WTRuck
::WutFace::WutFace
::YouWHY::4Head::YouWHY::4Head
::AMPEnergy::AMPEnergy
::AMPEnergyCherry::AMPEnergyCherry
::ANELE::ANELE
::ArgieB8::ArgieB8
::ArsonNoSexy::ArsonNoSexy
::AsianGlow::AsianGlow
::AthenaPMS::AthenaPMS
::BabyRage::BabyRage
::BatChest::BatChest
::BCouch::BCouch
::BCWarrior::BCWarrior
::BibleThump::BibleThump
::BiersDerp::BiersDerp
::BigBrother::BigBrother
::BionicBunion::BionicBunion
::BlargNaut::BlargNaut
::bleedPurple::bleedPurple
::BloodTrail::BloodTrail
::BORT::BORT
::BrainSlug::BrainSlug
::BrokeBack::BrokeBack
::BudBlast::BudBlast
::BuddhaBar::BuddhaBar
::BudStar::BudStar
::ChefFrank::ChefFrank
::cmonBruh::cmonBruh
::CoolCat::CoolCat
::CorgiDerp::CorgiDerp
::CougarHunt::CougarHunt
::DAESuppy::DAESuppy
::DalLOVE::DalLOVE
::DansGame::DansGame
::DatSheffy::DatSheffy
::DBstyle::DBstyle
::deExcite::deExcite
::deIlluminati::deIlluminati
::DendiFace::DendiFace
::DogFace::DogFace
::DOOMGuy::DOOMGuy
::duDudu::duDudu
::EagleEye::EagleEye
::EleGiggle::EleGiggle
::FailFish::FailFish
::FPSMarksman::FPSMarksman
::FrankerZ::FrankerZ
::FreakinStinkin::FreakinStinkin
::FUNgineer::FUNgineer
::FunRun::FunRun
::FutureMan::FutureMan
::FuzzyOtterOO::FuzzyOtterOO
::GingerPower::GingerPower
::GrammarKing::GrammarKing
::HassaanChop::HassaanChop
::HassanChop::HassanChop
::HeyGuys::HeyGuys
::HotPokket::HotPokket
::HumbleLife::HumbleLife
::ItsBoshyTime::ItsBoshyTime
::Jebaited::Jebaited
::JKanStyle::JKanStyle
::JonCarnage::JonCarnage
::KAPOW::KAPOW
::Kappa::Kappa
::KappaClaus::KappaClaus
::KappaPride::KappaPride
::KappaRoss::KappaRoss
::KappaWealth::KappaWealth
::Keepo::Keepo
::KevinTurtle::KevinTurtle
::Kippa::Kippa
::Kreygasm::Kreygasm
::Mau5::Mau5
::mcaT::mcaT
::MikeHogu::MikeHogu
::MingLee::MingLee
::MrDestructoid::MrDestructoid
::MVGame::MVGame
::NinjaTroll::NinjaTroll
::NomNom::NomNom
::NoNoSpot::NoNoSpot
::NotATK::NotATK
::NotLikeThis::NotLikeThis
::OhMyDog::OhMyDog
::OMGScoots::OMGScoots
::OneHand::OneHand
::OpieOP::OpieOP
::OptimizePrime::OptimizePrime
::OSfrog::OSfrog
::OSkomodo::OSkomodo
::OSsloth::OSsloth
::panicBasket::panicBasket
::PanicVis::PanicVis
::PartyTime::PartyTime
::PazPazowitz::PazPazowitz
::PeoplesChamp::PeoplesChamp
::PermaSmug::PermaSmug
::PeteZaroll::PeteZaroll
::PeteZarollTie::PeteZarollTie
::PicoMause::PicoMause
::PipeHype::PipeHype
::PJSalt::PJSalt
::PMSTwin::PMSTwin
::PogChamp::PogChamp
::Poooound::Poooound
::PraiseIt::PraiseIt
::PRChase::PRChase
::PunchTrees::PunchTrees
::PuppeyFace::PuppeyFace
::RaccAttack::RaccAttack
::RalpherZ::RalpherZ
::RedCoat::RedCoat
::ResidentSleeper::ResidentSleeper
::riPepperonis::riPepperonis
::RitzMitz::RitzMitz
::RuleFive::RuleFive
::SeemsGood::SeemsGood
::ShadyLulu::ShadyLulu
::ShazBotstix::ShazBotstix
::ShibeZ::ShibeZ
::SmoocherZ::SmoocherZ
::SMOrc::SMOrc
::SMSkull::SMSkull
::SoBayed::SoBayed
::SoonerLater::SoonerLater
::SriHead::SriHead
::SSSsss::SSSsss
::StinkyCheese::StinkyCheese
::StoneLightning::StoneLightning
::StrawBeary::StrawBeary
::SuperVinlin::SuperVinlin
::SwiftRage::SwiftRage
::TBCheesePull::TBCheesePull
::TBTacoLeft::TBTacoLeft
::TBTacoRight::TBTacoRight
::TF2John::TF2John
::TheRinger::TheRinger
::TheTarFu::TheTarFu
::TheThing::TheThing
::ThunBeast::ThunBeast
::TinyFace::TinyFace
::TooSpicy::TooSpicy
::TriHard::TriHard
::TTours::TTours
::twitchRaid::twitchRaid
::UleetBackup::UleetBackup
::UncleNox::UncleNox
::UnSane::UnSane
::VaultBoy::VaultBoy
::VoHiYo::VoHiYo
::Volcania::Volcania
::WholeWheat::WholeWheat
::WinWaker::WinWaker
::WTRuck::WTRuck
::WutFace::WutFace
::YouWHY::4Head::YouWHY::4Head
::AMPEnergy::AMPEnergy
::AMPEnergyCherry::AMPEnergyCherry
::ANELE::ANELE
::ArgieB8::ArgieB8
::ArsonNoSexy::ArsonNoSexy
::AsianGlow::AsianGlow
::AthenaPMS::AthenaPMS
::BabyRage::BabyRage
::BatChest::BatChest
::BCouch::BCouch
::BCWarrior::BCWarrior
::BibleThump::BibleThump
::BiersDerp::BiersDerp
::BigBrother::BigBrother
::BionicBunion::BionicBunion
::BlargNaut::BlargNaut
::bleedPurple::bleedPurple
::BloodTrail::BloodTrail
::BORT::BORT
::BrainSlug::BrainSlug
::BrokeBack::BrokeBack
::BudBlast::BudBlast
::BuddhaBar::BuddhaBar
::BudStar::BudStar
::ChefFrank::ChefFrank
::cmonBruh::cmonBruh
::CoolCat::CoolCat
::CorgiDerp::CorgiDerp
::CougarHunt::CougarHunt
::DAESuppy::DAESuppy
::DalLOVE::DalLOVE
::DansGame::DansGame
::DatSheffy::DatSheffy
::DBstyle::DBstyle
::deExcite::deExcite
::deIlluminati::deIlluminati
::DendiFace::DendiFace
::DogFace::DogFace
::DOOMGuy::DOOMGuy
::duDudu::duDudu
::EagleEye::EagleEye
::EleGiggle::EleGiggle
::FailFish::FailFish
::FPSMarksman::FPSMarksman
::FrankerZ::FrankerZ
::FreakinStinkin::FreakinStinkin
::FUNgineer::FUNgineer
::FunRun::FunRun
::FutureMan::FutureMan
::FuzzyOtterOO::FuzzyOtterOO
::GingerPower::GingerPower
::GrammarKing::GrammarKing
::HassaanChop::HassaanChop
::HassanChop::HassanChop
::HeyGuys::HeyGuys
::HotPokket::HotPokket
::HumbleLife::HumbleLife
::ItsBoshyTime::ItsBoshyTime
::Jebaited::Jebaited
::JKanStyle::JKanStyle
::JonCarnage::JonCarnage
::KAPOW::KAPOW
::Kappa::Kappa
::KappaClaus::KappaClaus
::KappaPride::KappaPride
::KappaRoss::KappaRoss
::KappaWealth::KappaWealth
::Keepo::Keepo
::KevinTurtle::KevinTurtle
::Kippa::Kippa
::Kreygasm::Kreygasm
::Mau5::Mau5
::mcaT::mcaT
::MikeHogu::MikeHogu
::MingLee::MingLee
::MrDestructoid::MrDestructoid
::MVGame::MVGame
::NinjaTroll::NinjaTroll
::NomNom::NomNom
::NoNoSpot::NoNoSpot
::NotATK::NotATK
::NotLikeThis::NotLikeThis
::OhMyDog::OhMyDog
::OMGScoots::OMGScoots
::OneHand::OneHand
::OpieOP::OpieOP
::OptimizePrime::OptimizePrime
::OSfrog::OSfrog
::OSkomodo::OSkomodo
::OSsloth::OSsloth
::panicBasket::panicBasket
::PanicVis::PanicVis
::PartyTime::PartyTime
::PazPazowitz::PazPazowitz
::PeoplesChamp::PeoplesChamp
::PermaSmug::PermaSmug
::PeteZaroll::PeteZaroll
::PeteZarollTie::PeteZarollTie
::PicoMause::PicoMause
::PipeHype::PipeHype
::PJSalt::PJSalt
::PMSTwin::PMSTwin
::PogChamp::PogChamp
::Poooound::Poooound
::PraiseIt::PraiseIt
::PRChase::PRChase
::PunchTrees::PunchTrees
::PuppeyFace::PuppeyFace
::RaccAttack::RaccAttack
::RalpherZ::RalpherZ
::RedCoat::RedCoat
::ResidentSleeper::ResidentSleeper
::riPepperonis::riPepperonis
::RitzMitz::RitzMitz
::RuleFive::RuleFive
::SeemsGood::SeemsGood
::ShadyLulu::ShadyLulu
::ShazBotstix::ShazBotstix
::ShibeZ::ShibeZ
::SmoocherZ::SmoocherZ
::SMOrc::SMOrc
::SMSkull::SMSkull
::SoBayed::SoBayed
::SoonerLater::SoonerLater
::SriHead::SriHead
::SSSsss::SSSsss
::StinkyCheese::StinkyCheese
::StoneLightning::StoneLightning
::StrawBeary::StrawBeary
::SuperVinlin::SuperVinlin
::SwiftRage::SwiftRage
::TBCheesePull::TBCheesePull
::TBTacoLeft::TBTacoLeft
::TBTacoRight::TBTacoRight
::TF2John::TF2John
::TheRinger::TheRinger
::TheTarFu::TheTarFu
::TheThing::TheThing
::ThunBeast::ThunBeast
::TinyFace::TinyFace
::TooSpicy::TooSpicy
::TriHard::TriHard
::TTours::TTours
::twitchRaid::twitchRaid
::UleetBackup::UleetBackup
::UncleNox::UncleNox
::UnSane::UnSane
::VaultBoy::VaultBoy
::VoHiYo::VoHiYo
::Volcania::Volcania
::WholeWheat::WholeWheat
::WinWaker::WinWaker
::WTRuck::WTRuck
::WutFace::WutFace
::YouWHY::YouWHY